version: "3"
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:3000
    container_name: mc-prod-frontend
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mc-prod-backend
    depends_on:
      - database
    env_file:
      - .env

  database:
    build:
      context: ./database
    container_name: mc-prod-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./database/data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro

  crawler:
    build:
      context: ./crawler
    container_name: mc-prod-crawler
    depends_on:
      - database
    env_file:
      - .env
