version: "3"
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - ${FRONTEND_PORT}:3000
    container_name: mc-frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    command: >
      sh -c "cd /app && npm install && npm start"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mc-backend
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:5000
    volumes:
      - ./backend:/app
    command: >
      sh -c "cd /app && npm install && npm run dev:start"

  database:
    build:
      context: ./database
    
    container_name: mc-database
    ports:
      - ${DATABASE_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}

    volumes:
      - ./database/data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro

  crawler:
    build:
      context: ./crawler
